<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net48</TargetFramework>
	  <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Kurinna.TaskPlanner.Domain.Models\Kurinna.TaskPlanner.Domain.Models.csproj" />

	</ItemGroup>
</Project>
